PRINT  MACRO PARA
       MOV DX,OFFSET PARA
       MOV AH,09H
       INT 21H
       ENDM

DATA   SEGMENT
       INFOR1 DB "ENTER DELAY TIME:$"
       INFOR2 DB 0AH,0DH, "200$"
       INFOR3 DB 0AH,0DH, "ABCDEF$"

DATA   ENDS 
CODE   SEGMENT
       ASSUME CS:CODE,DS:DATA   

START: 
    MOV AX,DATA
    MOV DS,AX
    PRINT INFOR1
    PRINT INFOR2
    PRINT INFOR3
    MOV AH,4CH
    INT 21H
CODE   ENDS
       END START