DATA SEGMENT
    DELAY DB 0
    MSG DB "Enter delay time as decimal number: $"
    ALPHABET DB 'ABCDEFGHIJKLMNOPQRSTUVWXYZ$'
DATA ENDS

CODE SEGMENT
ASSUME CS: CODE, DS: DATA
START:
    MOV AX, DATA
    MOV DS, AX
    LEA DX, MSG
    MOV AH, 09H
    INT 21H
    MOV AH, 02H
    MOV DL, 0AH
    INT 21H
    INT 21H
    MOV AH, 0Ah
    LEA DX, DELAY
    INT 21H
    LEA SI, DELAY
    MOV AL, [SI]
    CALL DEC_TO_BIN
    MOV CX, 26
    LEA SI, ALPHABET
OUTPUT_LOOP:
    MOV DL, [SI]
    MOV AH, 02H 
    INT 21H
    CALL DELAY_HELPER
    INC SI
    LOOP OUTPUT_LOOP
    MOV AH, 4CH
    INT 21H

DELAY_HELPER MACRO
    CALL DELAY
ENDM

DELAY PROC
    PUSH CX    
    MOV CX, 65533 
LOOP_DELAY:
    LOOP LOOP_DELAY  
    POP CX
    RET
DELAY ENDP

DEC_TO_BIN PROC
    PUSH AX
    MOV BX, 8000B
    XOR AL,AL
LOOP_DEC_TO_BIN:
    CMP AX, BX
    JL SKIP_BIT
    OR AL, BH
SKIP_BIT:
    SHR BX, 1
    CMP BX, 0
    JNE LOOP_DEC_TO_BIN